export const REGISTER_USER_ACCOUNT = "REGISTER_USER_ACCOUNT";
export const UPDATE_USER_ACCOUNT = "UPDATE_USER_ACCOUNT";
export const DELETE_USER_ACCOUNT = "DELETE_USER_ACCOUNT";
export const GET_ALL_USER_ACCOUNT = "GET_USER_ACCOUNT";
export const GET_USER_BY_ID_ACCOUNT = "GET_USER_BY_ID_ACCOUNT";
export const LOGIN_USER = "LOGIN_USER";
export const USER_REQUEST = "USER_REQUEST";
export const USER_REQUEST_FAIL = "USER_REQUEST_FAIL";
